-- =============================================
-- Hangfire Oracle Database Schema Installation Script
-- Compatible with Oracle 11g, 12c, 18c, 19c, 21c, 23ai
-- =============================================
-- Note: This script uses Oracle 11g compatible syntax.
-- For Oracle 12c+ specific features, see the version-specific scripts.

-- Jobs table - stores all background jobs
CREATE TABLE HF_JOB (
    ID NUMBER(19,0) NOT NULL,
    STATE_ID NUMBER(19,0) NULL,
    STATE_NAME NVARCHAR2(20) NULL,
    INVOCATION_DATA NCLOB NOT NULL,
    ARGUMENTS NCLOB NOT NULL,
    CREATED_AT TIMESTAMP(7) NOT NULL,
    EXPIRE_AT TIMESTAMP(7) NULL,
    CONSTRAINT PK_HF_JOB PRIMARY KEY (ID)
);

CREATE SEQUENCE HF_JOB_SEQ START WITH 1 INCREMENT BY 1 CACHE 20;

CREATE INDEX IX_HF_JOB_STATE_NAME ON HF_JOB (STATE_NAME);
CREATE INDEX IX_HF_JOB_EXPIRE_AT ON HF_JOB (EXPIRE_AT);

-- Job states table - stores job state history
CREATE TABLE HF_JOB_STATE (
    ID NUMBER(19,0) NOT NULL,
    JOB_ID NUMBER(19,0) NOT NULL,
    NAME NVARCHAR2(20) NOT NULL,
    REASON NVARCHAR2(100) NULL,
    CREATED_AT TIMESTAMP(7) NOT NULL,
    DATA NCLOB NULL,
    CONSTRAINT PK_HF_JOB_STATE PRIMARY KEY (ID),
    CONSTRAINT FK_HF_JOB_STATE_JOB FOREIGN KEY (JOB_ID) REFERENCES HF_JOB(ID) ON DELETE CASCADE
);

CREATE SEQUENCE HF_JOB_STATE_SEQ START WITH 1 INCREMENT BY 1 CACHE 20;

CREATE INDEX IX_HF_JOB_STATE_JOB_ID ON HF_JOB_STATE (JOB_ID);

-- Job parameters table - stores additional job parameters
CREATE TABLE HF_JOB_PARAMETER (
    ID NUMBER(19,0) NOT NULL,
    JOB_ID NUMBER(19,0) NOT NULL,
    NAME NVARCHAR2(40) NOT NULL,
    VALUE NCLOB NULL,
    CONSTRAINT PK_HF_JOB_PARAMETER PRIMARY KEY (ID),
    CONSTRAINT FK_HF_JOB_PARAMETER_JOB FOREIGN KEY (JOB_ID) REFERENCES HF_JOB(ID) ON DELETE CASCADE
);

CREATE SEQUENCE HF_JOB_PARAMETER_SEQ START WITH 1 INCREMENT BY 1 CACHE 20;

CREATE INDEX IX_HF_JOB_PARAMETER_JOB_ID ON HF_JOB_PARAMETER (JOB_ID);
CREATE INDEX IX_HF_JOB_PARAMETER_JOB_NAME ON HF_JOB_PARAMETER (JOB_ID, NAME);

-- Job queue table - stores jobs in queues
CREATE TABLE HF_JOB_QUEUE (
    ID NUMBER(19,0) NOT NULL,
    JOB_ID NUMBER(19,0) NOT NULL,
    QUEUE NVARCHAR2(50) NOT NULL,
    FETCHED_AT TIMESTAMP(7) NULL,
    FETCH_TOKEN NVARCHAR2(36) NULL,
    CONSTRAINT PK_HF_JOB_QUEUE PRIMARY KEY (ID)
);

CREATE SEQUENCE HF_JOB_QUEUE_SEQ START WITH 1 INCREMENT BY 1 CACHE 100;

-- Index for queue polling (compatible with all Oracle versions)
CREATE INDEX IX_HF_JOB_QUEUE_POLL ON HF_JOB_QUEUE (QUEUE, FETCHED_AT, ID);
CREATE INDEX IX_HF_JOB_QUEUE_TOKEN ON HF_JOB_QUEUE (FETCH_TOKEN);

-- Server table - stores registered Hangfire servers
CREATE TABLE HF_SERVER (
    ID NVARCHAR2(100) NOT NULL,
    DATA NCLOB NOT NULL,
    LAST_HEARTBEAT TIMESTAMP(7) NOT NULL,
    CONSTRAINT PK_HF_SERVER PRIMARY KEY (ID)
);

CREATE INDEX IX_HF_SERVER_LAST_HEARTBEAT ON HF_SERVER (LAST_HEARTBEAT);

-- Set table - stores sorted sets (scheduled jobs, etc.)
CREATE TABLE HF_SET (
    ID NUMBER(19,0) NOT NULL,
    KEY_NAME NVARCHAR2(100) NOT NULL,
    VALUE NVARCHAR2(256) NOT NULL,
    SCORE NUMBER(19,4) NOT NULL,
    EXPIRE_AT TIMESTAMP(7) NULL,
    CONSTRAINT PK_HF_SET PRIMARY KEY (ID)
);

CREATE SEQUENCE HF_SET_SEQ START WITH 1 INCREMENT BY 1 CACHE 100;

CREATE UNIQUE INDEX UX_HF_SET_KEY_VALUE ON HF_SET (KEY_NAME, VALUE);
CREATE INDEX IX_HF_SET_KEY_SCORE ON HF_SET (KEY_NAME, SCORE);
CREATE INDEX IX_HF_SET_EXPIRE_AT ON HF_SET (EXPIRE_AT);

-- Counter table - stores individual counter increments before aggregation
CREATE TABLE HF_COUNTER (
    ID NUMBER(19,0) NOT NULL,
    KEY_NAME NVARCHAR2(100) NOT NULL,
    VALUE NUMBER(10,0) NOT NULL,
    EXPIRE_AT TIMESTAMP(7) NULL,
    CONSTRAINT PK_HF_COUNTER PRIMARY KEY (ID)
);

CREATE SEQUENCE HF_COUNTER_SEQ START WITH 1 INCREMENT BY 1 CACHE 100;

CREATE INDEX IX_HF_COUNTER_KEY ON HF_COUNTER (KEY_NAME);
CREATE INDEX IX_HF_COUNTER_EXPIRE_AT ON HF_COUNTER (EXPIRE_AT);

-- Hash table - stores key-value pairs
CREATE TABLE HF_HASH (
    ID NUMBER(19,0) NOT NULL,
    KEY_NAME NVARCHAR2(100) NOT NULL,
    FIELD NVARCHAR2(100) NOT NULL,
    VALUE NCLOB NULL,
    EXPIRE_AT TIMESTAMP(7) NULL,
    CONSTRAINT PK_HF_HASH PRIMARY KEY (ID)
);

CREATE SEQUENCE HF_HASH_SEQ START WITH 1 INCREMENT BY 1 CACHE 100;

CREATE UNIQUE INDEX UX_HF_HASH_KEY_FIELD ON HF_HASH (KEY_NAME, FIELD);
CREATE INDEX IX_HF_HASH_EXPIRE_AT ON HF_HASH (EXPIRE_AT);

-- List table - stores lists
CREATE TABLE HF_LIST (
    ID NUMBER(19,0) NOT NULL,
    KEY_NAME NVARCHAR2(100) NOT NULL,
    POSITION NUMBER(10,0) DEFAULT 0 NOT NULL,
    VALUE NCLOB NULL,
    EXPIRE_AT TIMESTAMP(7) NULL,
    CONSTRAINT PK_HF_LIST PRIMARY KEY (ID)
);

CREATE SEQUENCE HF_LIST_SEQ START WITH 1 INCREMENT BY 1 CACHE 100;

CREATE INDEX IX_HF_LIST_KEY ON HF_LIST (KEY_NAME, POSITION);
CREATE INDEX IX_HF_LIST_EXPIRE_AT ON HF_LIST (EXPIRE_AT);

-- Aggregated counter table - stores counter aggregations
CREATE TABLE HF_AGGREGATED_COUNTER (
    ID NUMBER(19,0) NOT NULL,
    KEY_NAME NVARCHAR2(100) NOT NULL,
    VALUE NUMBER(19,0) NOT NULL,
    EXPIRE_AT TIMESTAMP(7) NULL,
    CONSTRAINT PK_HF_AGGREGATED_COUNTER PRIMARY KEY (ID)
);

CREATE SEQUENCE HF_AGG_COUNTER_SEQ START WITH 1 INCREMENT BY 1 CACHE 100;

CREATE UNIQUE INDEX UX_HF_AGG_COUNTER_KEY ON HF_AGGREGATED_COUNTER (KEY_NAME);
CREATE INDEX IX_HF_AGG_COUNTER_EXPIRE ON HF_AGGREGATED_COUNTER (EXPIRE_AT);

-- Distributed lock table
CREATE TABLE HF_DISTRIBUTED_LOCK (
    RESOURCE NVARCHAR2(100) NOT NULL,
    CREATED_AT TIMESTAMP(7) NOT NULL,
    CONSTRAINT PK_HF_DISTRIBUTED_LOCK PRIMARY KEY (RESOURCE)
);

CREATE INDEX IX_HF_DIST_LOCK_CREATED ON HF_DISTRIBUTED_LOCK (CREATED_AT);
