-- =============================================
-- Hangfire Oracle Database Schema Uninstallation Script
-- =============================================

-- Drop tables in reverse order to respect foreign key constraints
DROP TABLE HF_DISTRIBUTED_LOCK;
DROP TABLE HF_AGGREGATED_COUNTER;
DROP TABLE HF_LIST;
DROP TABLE HF_HASH;
DROP TABLE HF_COUNTER;
DROP TABLE HF_SET;
DROP TABLE HF_SERVER;
DROP TABLE HF_JOB_QUEUE;
DROP TABLE HF_JOB_PARAMETER;
DROP TABLE HF_JOB_STATE;
DROP TABLE HF_JOB;

-- Drop sequences
DROP SEQUENCE HF_JOB_SEQ;
DROP SEQUENCE HF_JOB_STATE_SEQ;
DROP SEQUENCE HF_JOB_PARAMETER_SEQ;
DROP SEQUENCE HF_JOB_QUEUE_SEQ;
DROP SEQUENCE HF_SET_SEQ;
DROP SEQUENCE HF_COUNTER_SEQ;
DROP SEQUENCE HF_HASH_SEQ;
DROP SEQUENCE HF_LIST_SEQ;
DROP SEQUENCE HF_AGG_COUNTER_SEQ;
